Repository ThreeGuysOrg/FoodManager-Backend, pull requests merged in 2023-03, with the labels that each got.

#5 4 create ci for net6 backend and test sonarcloud analyze for backend repo
  .github/workflows/dotnet.yaml
  .github/workflows/dotnet.yml
  .vscode/settings.json
  README.md
Labels: task, review

#14 Created default dockerfile temp
  Dockerfile
Labels: review

#15 Add docker build and push ci
  .github/workflows/docker-build.yaml
  .github/workflows/docker-push.yaml
  .github/workflows/dotnet-test.yaml
  .github/workflows/dotnet.yaml
  .github/workflows/sonar.yaml
Labels: review

#17 Update docker ci logic
  .github/workflows/docker-build.yaml
  .github/workflows/docker-push.yaml
  .github/workflows/docker-test.yaml
  .github/workflows/docker.yaml
  .github/workflows/dotnet-test.yaml
  .github/workflows/dotnet.yaml
  .github/workflows/linter.yaml
  .github/workflows/sonar.yaml
Labels: backend

#19 Added validation for all models
  FoodManagerApi/DAL/Models/Manufacturer.cs
  FoodManagerApi/DAL/Models/Meal.cs
  FoodManagerApi/DAL/Models/NutritionalValue.cs
  FoodManagerApi/DAL/Models/Product.cs
  FoodManagerApi/DAL/Models/User.cs
  FoodManagerApi/FoodManagerApi/Models/ManufacturerDto.cs
  FoodManagerApi/FoodManagerApi/Models/MealDto.cs
  FoodManagerApi/FoodManagerApi/Models/NutritionalValueDto.cs
  FoodManagerApi/FoodManagerApi/Models/ProductDto.cs
  FoodManagerApi/FoodManagerApi/Models/UserDto.cs
Labels: backend
